### ISSUE TITLE
attempts to load non-php template files

### ISSUE THREAD

**Issue by daveriedstra** [MWDelaney/sage-acf-wp-blocks#11]
Thanks for writing this. I'm just trying it out and it looks like the library is trying to load the vim temp file for my test block template:

```

Warning: fopen(): Filename cannot be empty in /srv/www/wordpress-two/public_html/wp-includes/functions.php on line 5462

Warning: fread() expects parameter 1 to be resource, boolean given in /srv/www/wordpress-two/public_html/wp-includes/functions.php on line 5465

Warning: fclose() expects parameter 1 to be resource, boolean given in /srv/www/wordpress-two/public_html/wp-includes/functions.php on line 5468

Sage › Error
Block title missing

This block needs a title: views/blocks/.test.blade.php.swp

roots.io/sage/docs/
```

**Comment by dotsam** [comment]
+1. Tried to create the views/blocks folder with a .gitkeep folder for version control, and it errored out in the same way.

Will probably need some more checks when looping through the DirectoryIterator.

**Comment by erikhartin** [comment]
+1. having browsed the folder in Finder by mistake leaving a .DS_STORE file creates same issue

**Comment by xaqrox** [comment]
For those who are subscribed, that PR should solve this issue.
