### ISSUE TITLE
Add filter for block data.

### ISSUE THREAD

**Issue by xaqrox** [MWDelaney/sage-acf-wp-blocks#22]
In the absence of a solution for #5, it would be nice if we could still get our hands on block data so we could avoid processing stuff in the templates. Something like this, for a block defined by `my-block.blade.php`:

```php
add_filter('sage/blocks/my-block/data', function ($block) { // Do your thing here. });
```
PR incoming.

**Comment by MWDelaney** [comment]
Closed by #23
