### ISSUE TITLE
Hide default blocks

### ISSUE THREAD

**Issue by basvandertogt** [MWDelaney/sage-acf-wp-blocks#41]
What is a proper way to hide the default Gutenberg Blocks in combination with this plugin?

**Comment by skynetpy1** [comment]
You can allow blocks with this hook: 

add_filter( 'allowed_block_types', 'AllowBlockTypes' );

function AllowBlockTypes($allowed_blocks)	{
		return [
			'core/image',
			'core/video',
			'core/paragraph',
			'core/heading',
			'core/list',
			'acf/custom-block', // custom-block is block file name ( i.e custom-block.blade.php)
		];
}

**Comment by basvandertogt** [comment]
Tnx!
