### ISSUE TITLE
Template location mismatch when using 'sage-acf-gutenberg-blocks-templates' filter

### ISSUE THREAD

**Issue by guimachiavelli** [MWDelaney/sage-acf-wp-blocks#45]
When using the filter `sage-acf-gutenberg-blocks-templates` to override the template location from `views/blocks` to e.g. `views/gutenberg`, `sage_blocks_callback` will still always and only look for template files inside `views/blocks`.

Is this by design? It definitely wasn’t what I was expecting and it took me some time to realise that, even if the block had been registered via the metadata inside a file in `views/gutenberg`, the template itself still had to sit inside `views/blocks`. 

Or am I missing something here?

**Comment by robmeijerink** [comment]
Hi, thank you for reporting this bug. I don't think this was done on purpose, so I made a fix and a PR. :)

**Comment by guimachiavelli** [comment]
Brilliant, thanks for taking the time to look into it =)
