### ISSUE TITLE
No Block Types Exist

### ISSUE THREAD

**Issue by jasperf** [MWDelaney/sage-acf-wp-blocks#47]
I added the plugin, added the example data to `block.blade.php` inside `resources/views/blocks/testimonial` and added real block data to `testimonial.blade.php` in the same directory. But now when I add a new field in Advanced Custom Fields I am told no block type exists? What am I missing here?

**Comment by jasperf** [comment]
Realized I did not need an extra `block.blade.php`. Tried without it and testimonial inside the `blocks` directory instead of a sub directory.  Still I am seeing `no block types exist` inside the Advanced Custom Fields` Fields builder under location. So I must be missing something here. But what?

**Comment by jasperf** [comment]
When I use the Advanced Custom FIelds as a must-use plugin `mu-plugins` the blocks do load. So it seems if I load it form the theme using `filters.php` it hooks into too late perhaps?

**Comment by LazyRecon** [comment]
if i load acf from theme folder like specified [here](https://www.advancedcustomfields.com/resources/including-acf-within-a-plugin-or-theme/) blocks are not loaded. I move move it to plugin folder.
