### ISSUE TITLE
Align text and Align content not adding classes

### ISSUE THREAD

**Issue by daniela-waara** [MWDelaney/sage-acf-wp-blocks#58]
```
SupportsAlignContent: true
SupportsAlignText: true
```
The selector appears in the editor but doesn't seem to add any new align-classes in `$block['classes']` when chosen.
How do I use them?

**Comment by colinswinney** [comment]
@daniela-waara did you ever get this figured out by chance?  I'm having the same problem.

**Comment by daniela-waara** [comment]
@colinswinney yes, in the end i figured out that you needed to use `$block['align']`, `$block['align_content']` and `$block['align_text']` to get the positions

**Comment by colinswinney** [comment]
@daniela-waara you're awesome, thank you for responding so quickly.
